" kr4nd0m's vimrc
set encoding=utf-8
scriptencoding utf-8

" Auto install plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.config//nvim/autoload/plug.vim --create-dirs
           \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    augroup PLUG
        au!
        autocmd VimEnter * PlugInstall
    augroup END
endif

" Plugins {{{

call plug#begin('~/.vim/plugged')


Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    nnoremap ,. :FZF<CR>

Plug 'gabesoft/vim-ags'
    let g:ags_winheight = '20'

Plug 'majutsushi/tagbar'
    let g:tagbar_autoclose = 1
    set tags=./tags,tags;$HOME
    nnoremap ,, :Tags<CR>
    nnoremap ,t :TagbarToggle<CR>
    command! GenerateTags :call utils#run_ctags()
    nnoremap <Leader>tt :GenerateTags<CR>

Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
    nnoremap ,n :NERDTreeFind<CR>
    nnoremap ,m :NERDTreeToggle<CR>
	let NERDTreeQuitOnOpen = 1
	let NERDTreeIgnore = ['\.pyc$', '__pycache__']

	" NERDTress File highlighting
	function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
	 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
	 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
	endfunction

	call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
	call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
	call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
	call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
	call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
	call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
	call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
	call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')

Plug 'w0rp/ale'
Plug 'Valloric/YouCompleteMe', {'do': './install.py'}
    let g:ycm_python_binary_path = 'python'

Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/incsearch.vim'
	map /  <Plug>(incsearch-forward)
	map ?  <Plug>(incsearch-backward)
	map g/ <Plug>(incsearch-stay)
	map z/ <Plug>(incsearch-fuzzy-/)
	map z? <Plug>(incsearch-fuzzy-?)
	map zg/ <Plug>(incsearch-fuzzy-stay)

	" incsearch.vim x fuzzy x vim-easymotion

	function! s:config_easyfuzzymotion(...) abort
	  return extend(copy({
		\   'converters': [incsearch#config#fuzzy#converter()],
		\   'modules': [incsearch#config#easymotion#module()],
		\   'keymap': {"\<CR>": '<Over>(easymotion)'},
		\   'is_expr': 0,
		\   'is_stay': 1
		\ }), get(a:, 1, {}))
	endfunction

	noremap <silent><expr> <Space>/ incsearch#go(<SID>config_easyfuzzymotion())

Plug 'xolox/vim-misc' " Dependency for vim-session
Plug 'xolox/vim-session'
    let g:session_autoload = 'no'
    let g:session_autosave = 'no'

Plug 'fakeezz/marvim'
    let g:marvim_prefix_on_load = 0

Plug 'junegunn/seoul256.vim'
    let g:seoul256_background = 238
    colo seoul256

Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
    vmap s <Plug>VSurround
    nmap ys <Plug>Ysurroundw

Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'terryma/vim-multiple-cursors'
Plug 'ryanoasis/vim-devicons'
Plug 'christoomey/vim-tmux-navigator'
Plug 'iamcco/markdown-preview.vim'

filetype plugin indent on
call plug#end()

" General configs
syntax on
syntax enable
set nofoldenable
set foldmethod=indent
set nocompatible
set encoding=utf8
set nowrap
set backspace=indent,eol,start
set splitright
set splitbelow
set noswapfile
set number
set relativenumber
set ruler
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set laststatus=2
set cursorline

command! PrettyXML call utils#do_pretty_xml()

noremap <Leader>cp "+y:echo 'selection copied!'<CR>
noremap <Leader>cl <Esc>0v$h"+y:echo 'line copied!'<CR>
nnoremap <Leader>cw viw"+y:echo 'word copied!'<CR>
vnoremap // y/<C-R>"<CR>

" Source .vimrc
nnoremap <Leader>vs :source ~/.vimrc<CR>

" Zoom
nnoremap <Leader>z :call utils#window_zoom()<CR>

" Move line up/down
nnoremap <Leader>- :m-2<CR>
nnoremap <Leader>_ :m+1<CR>
" Redo
nnoremap U :red<CR>
" Replace on visual selection
vnoremap <C-R> :s/\%V

" tags -> jumps
nnoremap <C-]> <Esc>:exe "tjump " . expand("<cword>")<Esc>
